require:
  - rubocop-rails
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.3
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema*.rb"
    - "node_modules/**/*"
    - "db/migrate/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "bin/*"
    - "config/**/*"
    - "gems/*"
    - "app/controllers/admin/*"
    - "app/helpers/admin/*"
    - "app/controllers/admin/admins/*"

Metrics/AbcSize:
  Max: 100

Metrics/MethodLength:
  Max: 100

Metrics/ClassLength:
  Max: 1000

Metrics/CyclomaticComplexity:
  Max: 100

Style/CombinableLoops:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 100

Rails/SkipsModelValidations:
  Enabled: false

Style/Documentation:
  Enabled: false
