require:
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.3
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema*.rb"
    - "node_modules/**/*"
    - "db/migrate/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "bin/*"
    - "config/**/*"
    - "gems/*"
    - "app/controllers/admin/*"
    - "app/helpers/admin/*"
    - "app/controllers/admin/admins/*"

Documentation:
  Enabled: false