@startuml

!include ./config/default.inc

entity users {
    + id: string [PK]
    --
    * username: string, not null
    * email: string
    * firebase_id: string, not null
    * twitter_id: string
    * google_id: string
    created_at: datetime
    updated_at: datetime
}

entity users_events {
    + id: integer [PK]
    --
    * user_id: integer, not null [FK]
    * event_id: integer, not null [FK]
    label: integer, not null
    created_at: datetime
    updated_at: datetime
}

entity events {
    + id: integer [PK]
    --
    * name: string, not null
    start_at: datetime
    end_at: datetime
    image_url: string
    location_name: string
    location_address: string
    location_latitude: float
    location_longitude: float
    group_num: integer
    total_cost: integer
    questionnaire_url: string
    pattern: integer
    created_at: datetime
    updated_at: datetime
}

entity notifications {
    + id: integer [PK]
    --
    * event_id: integer, not null [FK]
    title: string, not null
    contents: string, not null
    created_at: datetime
    updated_at: datetime
}

entity attend_statuses {
    + id: integer [PK]
    --
    * schedule_candidate_id: integer, not null [FK]
    * user_id: string, not null [FK]
    status: integer, not null
    created_at: datetime
    updated_at: datetime
}

entity schedule_candidates {
    + id: integer [PK]
    --
    * event_id: integer, not null [FK]
    start_at: datetime
    end_at: datetime
    created_at: datetime
    updated_at: datetime
}

users ||-do-o{ users_events: id:user_id
users_events  }|-do-|| events: event_id:id
events ||-do-o{ notifications: id: event_id
users ||-ri-o{ attend_statuses: id:user_id
attend_statuses }o-do-|| schedule_candidates: schedule_candidate_id:id
schedule_candidates }o-do-|| events: event_id:id

@enduml
